// This file is generated by Scripts/update-version.ps1.

using System.Reflection;

[assembly: AssemblyVersion("2.0.0.0")]
[assembly: AssemblyFileVersion("2.0.0.0")]
[assembly: AssemblyInformationalVersion("2+v1-3-gd8099fa")]
