param(
    [ValidatePattern('^\d+(\.\d+){0,3}$')]
    [string]$Version = "1",
    [string]$ProjectName = "QuickLook.Plugin.EpubViewer2"
)

$ErrorActionPreference = "Stop"

$root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$projectDirectory = Join-Path $root $ProjectName
$versionSource = Join-Path $projectDirectory "GitVersion.cs"
$metadataTemplate = Join-Path $projectDirectory "QuickLook.Plugin.Metadata.Base.config"
$metadataOutput = Join-Path $projectDirectory "QuickLook.Plugin.Metadata.config"

if (-not (Test-Path $metadataTemplate)) {
    throw "메타데이터 템플릿을 찾을 수 없습니다: $metadataTemplate"
}

$versionForAssembly = if ($Version.Contains(".")) { $Version } else { "$Version.0" }
$parsedVersion = [Version]::Parse($versionForAssembly)
$build = if ($parsedVersion.Build -ge 0) { $parsedVersion.Build } else { 0 }
$revision = if ($parsedVersion.Revision -ge 0) { $parsedVersion.Revision } else { 0 }
$assemblyVersion = "$($parsedVersion.Major).$($parsedVersion.Minor).$build.$revision"

$previousErrorActionPreference = $ErrorActionPreference
$ErrorActionPreference = "Continue"
$gitRevision = (& git -C $root describe --always --tags 2>$null)
$gitExitCode = $LASTEXITCODE
$ErrorActionPreference = $previousErrorActionPreference
if ($gitExitCode -ne 0 -or [string]::IsNullOrWhiteSpace($gitRevision)) {
    $gitRevision = "unknown"
}
$informationalVersion = "$Version+$gitRevision"

$source = @"
// This file is generated by Scripts/update-version.ps1.

using System.Reflection;

[assembly: AssemblyVersion("$assemblyVersion")]
[assembly: AssemblyFileVersion("$assemblyVersion")]
[assembly: AssemblyInformationalVersion("$informationalVersion")]
"@

$source | Out-File $versionSource -Encoding utf8

$metadata = [xml](Get-Content -Raw $metadataTemplate)
$metadata.Metadata.Version = $Version
$metadata.Save($metadataOutput)

Write-Host "Plugin version: $Version"
Write-Host "Assembly version: $assemblyVersion"
Write-Host "Informational version: $informationalVersion"
